---
- name: Instalar Apache
  apt:
    name: apache2
    state: present

- name: Copiar archivos del frontend
  copy:
    src: "../../../frontend/"
    dest: /var/www/html/
    owner: www-data
    group: www-data
    mode: '0644'

- name: Habilitar módulos de proxy
  apache2_module:
    name: "{{ item }}"
    state: present
  loop:
    - proxy
    - proxy_http

- name: Configurar proxy para API  
  copy:
    content: |
      ProxyPass "/usuarios" "http://{{ groups['backends'][0] }}:5000/usuarios"
      ProxyPassReverse "/usuarios" "http://{{ groups['backends'][0] }}:5000/usuarios"
    dest: /etc/apache2/conf-available/proxy-api.conf

- name: Habilitar configuración proxy
  command: a2enconf proxy-api

- name: Reiniciar Apache
  service:
    name: apache2
    state: restarted

- name: Verificar estado de Apache
  service:
    name: apache2
    state: started
    enabled: yes