---
- name: Instalar Apache
  apt:
    name: apache2
    state: present

- name: Habilitar módulos de proxy
  apache2_module:
    name: "{{ item }}"
    state: present
  loop:
    - proxy
    - proxy_http
    - proxy_balancer
    - lbmethod_byrequests

- name: Configurar balanceo para frontends
  copy:
    content: |
      <Proxy "balancer://frontend_cluster">
        BalancerMember http://{{ groups['frontends'][0] }}:80
        BalancerMember http://{{ groups['frontends'][1] }}:80
        ProxySet lbmethod=byrequests
      </Proxy>

      ProxyPass "/" "balancer://frontend_cluster/"
      ProxyPassReverse "/" "balancer://frontend_cluster/"
    dest: /etc/apache2/conf-available/load-balancer.conf

- name: Habilitar configuración de balanceo
  command: a2enconf load-balancer

- name: Reiniciar Apache
  service:
    name: apache2
    state: restarted

- name: Verificar estado de Apache
  service:
    name: apache2
    state: started
    enabled: yes